/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.waterwaveprogress;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.TiApplication;

import android.widget.LinearLayout;
import android.widget.LinearLayout.LayoutParams;
import android.app.Activity;
import cn.modificator.waterwave_progress.*;

@Kroll.proxy(creatableInModule = WaterwaveprogressModule.class)
public class ViewProxy extends TiViewProxy {
	// Standard Debugging variables
	private static final String LCAT = "WaWaView";

	WaterWaveProgress progressView;
	private int mRingColor, mRingBgColor, mWaterColor, mWaterBgColor,
			mFontSize, mTextColor;
	float mCrestCount = 1.5f;
	int mProgress = 10, mMaxProgress = 100;
	private float mRingWidth, mRing2WaterWidth;
	private boolean mShowNumerical = true, mShowRing = true;

	private int mWaveFactor = 0;
	private boolean mIsWaving = false;
	private float mAmplitude = 30.0F; // 20F
	private float mWaveSpeed = 0.070F; // 0.020F
	private int mWaterAlpha = 255; // 255

	private class WWPView extends TiUIView {
		public WWPView(TiViewProxy proxy) {
			super(proxy);
			LayoutParams lp = new LayoutParams(LayoutParams.WRAP_CONTENT,
					LayoutParams.WRAP_CONTENT);
			LinearLayout container = new LinearLayout(proxy.getActivity());
			container.setLayoutParams(lp);
			progressView = new WaterWaveProgress(TiApplication.getInstance()
					.getApplicationContext());
			progressView.setShowRing(mShowRing);
			progressView.setShowNumerical(mShowNumerical);
			progressView.setCrestCount(mCrestCount);
			progressView.setProgress(mProgress);
			progressView.setRingWidth(mRingWidth);
			progressView.setCrestCount(mCrestCount);
			progressView.setAmplitude(mAmplitude);
			progressView.setWaterColor(mWaterColor);
			progressView.setWaterBgColor(mWaterBgColor);
			progressView.setRingColor(mRingColor);
			progressView.setRingBgColor(mRingBgColor);
			progressView.setFontSize(mFontSize);
			progressView.setTextColor(mTextColor);
			progressView.setRingWidth(mRingWidth);
			progressView.setRing2WaterWidth(mRing2WaterWidth);
			progressView.setIsWaving(mIsWaving);
			progressView.setWaveFactor(mWaveFactor);
			progressView.setWaveSpeed(mWaveSpeed);
			progressView.setWaterAlpha(mWaterAlpha);
			container.addView(progressView);
			setNativeView(container);
		}

		@Override
		public void processProperties(KrollDict d) {
			super.processProperties(d);
		}
	}

	// Constructor
	public ViewProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		TiUIView view = new WWPView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;

		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
		if (options.containsKeyAndNotNull("progress")) {
			mProgress = TiConvert.toInt(options, "progress");
		}
		if (options.containsKeyAndNotNull("maxProgress")) {
			mMaxProgress = TiConvert.toInt(options, "maxProgress");
		}
		if (options.containsKeyAndNotNull("ringWidth")) {
			mRingWidth = TiConvert.toFloat(options, "ringWidth");
		}
		if (options.containsKeyAndNotNull("fontSize")) {
			mFontSize = TiConvert.toInt(options, "fontSize");
		}
		if (options.containsKeyAndNotNull("ring2WaterWidth")) {
			mRing2WaterWidth = TiConvert.toFloat(options, "ring2WaterWidth");
		}
		if (options.containsKeyAndNotNull("ringColor")) {
			mRingColor = TiConvert.toColor(options, "ringColor");
		}
		if (options.containsKeyAndNotNull("ringBgColor")) {
			mRingBgColor = TiConvert.toColor(options, "ringBgColor");
		}
		if (options.containsKeyAndNotNull("waterColor")) {
			mWaterColor = TiConvert.toColor(options, "waterColor");
		}
		if (options.containsKeyAndNotNull("waterBgColor")) {
			mWaterBgColor = TiConvert.toColor(options, "waterBgColor");
		}
		if (options.containsKeyAndNotNull("textColor")) {
			mTextColor = TiConvert.toColor(options, "textColor");
		}
		if (options.containsKeyAndNotNull("showNumerical")) {
			mShowNumerical = TiConvert.toBoolean(options, "showNumerical");
		}
		if (options.containsKeyAndNotNull("showRing")) {
			mShowRing = TiConvert.toBoolean(options, "showRing");
		}
		if (options.containsKeyAndNotNull("crestCount")) {
			mCrestCount = TiConvert.toFloat(options, "crestCount");
		}
		if (options.containsKeyAndNotNull("amplitude")) {
			mAmplitude = TiConvert.toFloat(options, "amplitude");
		}
		if (options.containsKeyAndNotNull("α")) {
			mWaterAlpha = TiConvert.toInt(options, "α");
		}
		if (options.containsKeyAndNotNull("waveFactor")) {
			mWaveFactor = TiConvert.toInt(options, "waveFactor");
		}

	}

	@Kroll.method
	public void hideNumerical() {
		progressView.setShowNumerical(false);
	}

	@Kroll.method
	public void showNumerical() {
		progressView.setShowNumerical(true);
	}

	@Kroll.method
	public void setShowRingVisibility(boolean arg) {
		progressView.setShowRing(arg);
	}

	@Kroll.method
	public void hideRing() {
		progressView.setShowRing(false);
	}

	@Kroll.method
	public void showRing() {
		progressView.setShowRing(true);
	}

	@Kroll.method
	public void setCrestCount(int crestCount) {
		progressView.setCrestCount(crestCount);
	}

	@Kroll.method
	public void setProgress(int arg) {
		Log.d(LCAT, "mProgress=" + arg);
		progressView.setProgress(arg);
	}

	@Kroll.method
	public void setRingWidth(float width) {
		progressView.setRingWidth(width);
	}

	@Kroll.method
	public void setCrestCount(float crestCount) {
		progressView.setCrestCount(crestCount);
	}

	@Kroll.method
	public void setAmplitude(float amp) {
		progressView.setAmplitude(amp);
	}

	@Kroll.method
	public void setWaveSpeed(float arg) {
		progressView.setWaveSpeed(arg);
	}

	@Kroll.method
	public void setWaterAlpha(float arg) {
		progressView.setWaterAlpha(arg);
	}
}